[project]
name = "heimdex-common"
version = "0.0.0"
description = "Shared utilities and models for Heimdex."
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.9,<3.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
