[project]
name = "heimdex-common"
version = "0.0.0"
description = "Shared utilities and models for Heimdex."
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.9,<3.0.0",
    "sqlalchemy>=2.0.0,<3.0.0",
    "alembic>=1.13.0,<2.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "pydantic-settings>=2.0.0,<3.0.0",
    "redis>=5.0.0,<6.0.0",
    "requests>=2.31.0,<3.0.0",
    "google-cloud-storage>=2.10.0,<3.0.0",
    "packaging>=23.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
