[project]
name = "heimdex-api"
version = "0.0.0"
description = "Placeholder FastAPI service for Heimdex."
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
